name: pytorch
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10
  - h5py
  - opencv
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - pillow
  - pytest
  - plotly
  - notebook
  - tqdm
